package online.templab.flippedclass.dao;

import java.util.List;
import online.templab.flippedclass.domain.Klass;

public interface KlassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    int insert(Klass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    Klass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    List<Klass> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    int updateByPrimaryKey(Klass record);
}