package online.templab.flippedclass.dao;

import java.util.List;
import online.templab.flippedclass.domain.KlassTeam;

public interface KlassTeamDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    int deleteById(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    int insert(KlassTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    KlassTeam getById(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    List<KlassTeam> listAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    int updateById(KlassTeam record);
}