package online.templab.flippedclass.dao;

import java.util.List;
import online.templab.flippedclass.domain.KlassTeam;

public interface KlassTeamDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated
     */
    int insert(KlassTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated
     */
    KlassTeam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated
     */
    List<KlassTeam> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KlassTeam record);
}