package online.templab.flippedclass.dao;

import java.util.List;
import online.templab.flippedclass.domain.KlassStudent;

public interface KlassStudentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_student
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_student
     *
     * @mbg.generated
     */
    int insert(KlassStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_student
     *
     * @mbg.generated
     */
    KlassStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_student
     *
     * @mbg.generated
     */
    List<KlassStudent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KlassStudent record);
}