package online.templab.flippedclass.dao;

import java.util.List;
import online.templab.flippedclass.domain.KlassTeam;

public interface KlassTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    int insert(KlassTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    KlassTeam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    List<KlassTeam> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_team
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    int updateByPrimaryKey(KlassTeam record);
}