package online.templab.flippedclass.dao;

import java.util.List;
import online.templab.flippedclass.domain.Material;

public interface MaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    int insert(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    Material selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    List<Material> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    int updateByPrimaryKey(Material record);
}