package online.templab.flippedclass.dao;

import java.util.List;
import online.templab.flippedclass.domain.Presentation;

public interface PresentationDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presentation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presentation
     *
     * @mbg.generated
     */
    int insert(Presentation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presentation
     *
     * @mbg.generated
     */
    Presentation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presentation
     *
     * @mbg.generated
     */
    List<Presentation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presentation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Presentation record);
}