package online.templab.flippedclass.dao;

import java.util.List;
import online.templab.flippedclass.domain.Report;

public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    Report selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    List<Report> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    int updateByPrimaryKey(Report record);
}