package online.templab.flippedclass.dao;

import java.util.List;
import online.templab.flippedclass.domain.Round;

public interface RoundDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round
     *
     * @mbg.generated
     */
    int insert(Round record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round
     *
     * @mbg.generated
     */
    Round selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round
     *
     * @mbg.generated
     */
    List<Round> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Round record);
}