package online.templab.flippedclass.dao;

import java.util.List;
import online.templab.flippedclass.domain.ShareApplication;

public interface ShareApplicationDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_application
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_application
     *
     * @mbg.generated
     */
    int insert(ShareApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_application
     *
     * @mbg.generated
     */
    ShareApplication selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_application
     *
     * @mbg.generated
     */
    List<ShareApplication> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_application
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShareApplication record);
}