package online.templab.flippedclass.dao;

import java.util.List;
import online.templab.flippedclass.domain.StudentKlass;

public interface StudentKlassDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_klass
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_klass
     *
     * @mbg.generated
     */
    int insert(StudentKlass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_klass
     *
     * @mbg.generated
     */
    StudentKlass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_klass
     *
     * @mbg.generated
     */
    List<StudentKlass> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_klass
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StudentKlass record);
}