package online.templab.flippedclass.dao;

import java.util.List;
import online.templab.flippedclass.domain.TeamRule;

public interface TeamRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_rule
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_rule
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    int insert(TeamRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_rule
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    TeamRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_rule
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    List<TeamRule> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_rule
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    int updateByPrimaryKey(TeamRule record);
}