package online.templab.flippedclass.domain;

import java.io.Serializable;

public class Course implements Serializable {

    /**
     * 序列化编号
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.intro
     *
     * @mbg.generated
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.need_team
     *
     * @mbg.generated
     */
    private Byte needTeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.share_team
     *
     * @mbg.generated
     */
    private Byte shareTeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.share_seminar
     *
     * @mbg.generated
     */
    private Byte shareSeminar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.present_weight
     *
     * @mbg.generated
     */
    private Long presentWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.quetion_weight
     *
     * @mbg.generated
     */
    private Long quetionWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.report_weight
     *
     * @mbg.generated
     */
    private Long reportWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.team_rule_id
     *
     * @mbg.generated
     */
    private Integer teamRuleId;


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    public Byte getNeedTeam() {
        return needTeam;
    }

    public void setNeedTeam(Byte needTeam) {
        this.needTeam = needTeam;
    }

    public Byte getShareTeam() {
        return shareTeam;
    }

    public void setShareTeam(Byte shareTeam) {
        this.shareTeam = shareTeam;
    }

    public Byte getShareSeminar() {
        return shareSeminar;
    }

    public void setShareSeminar(Byte shareSeminar) {
        this.shareSeminar = shareSeminar;
    }

    public Long getPresentWeight() {
        return presentWeight;
    }

    public void setPresentWeight(Long presentWeight) {
        this.presentWeight = presentWeight;
    }

    public Long getQuetionWeight() {
        return quetionWeight;
    }

    public void setQuetionWeight(Long quetionWeight) {
        this.quetionWeight = quetionWeight;
    }

    public Long getReportWeight() {
        return reportWeight;
    }

    public void setReportWeight(Long reportWeight) {
        this.reportWeight = reportWeight;
    }

    public Integer getTeamRuleId() {
        return teamRuleId;
    }

    public void setTeamRuleId(Integer teamRuleId) {
        this.teamRuleId = teamRuleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", intro=").append(intro);
        sb.append(", needTeam=").append(needTeam);
        sb.append(", shareTeam=").append(shareTeam);
        sb.append(", shareSeminar=").append(shareSeminar);
        sb.append(", presentWeight=").append(presentWeight);
        sb.append(", quetionWeight=").append(quetionWeight);
        sb.append(", reportWeight=").append(reportWeight);
        sb.append(", teamRuleId=").append(teamRuleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}