package online.templab.flippedclass.domain;

import java.io.Serializable;

public class KlassStudent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klass_student.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klass_student.klass_id
     *
     * @mbg.generated
     */
    private Integer klassId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klass_student.student_id
     *
     * @mbg.generated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table klass_student
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klass_student.id
     *
     * @return the value of klass_student.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klass_student.id
     *
     * @param id the value for klass_student.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klass_student.klass_id
     *
     * @return the value of klass_student.klass_id
     *
     * @mbg.generated
     */
    public Integer getKlassId() {
        return klassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klass_student.klass_id
     *
     * @param klassId the value for klass_student.klass_id
     *
     * @mbg.generated
     */
    public void setKlassId(Integer klassId) {
        this.klassId = klassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klass_student.student_id
     *
     * @return the value of klass_student.student_id
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klass_student.student_id
     *
     * @param studentId the value for klass_student.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klass_student
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", klassId=").append(klassId);
        sb.append(", studentId=").append(studentId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}