package online.templab.flippedclass.domain;

import java.io.Serializable;
import java.util.Date;

public class Presentation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.team_id
     *
     * @mbg.generated
     */
    private Integer teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.score
     *
     * @mbg.generated
     */
    private Long score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.report_score
     *
     * @mbg.generated
     */
    private Long reportScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.seating_order
     *
     * @mbg.generated
     */
    private Byte seatingOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.seminard
     *
     * @mbg.generated
     */
    private Byte seminard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.material_filename
     *
     * @mbg.generated
     */
    private String materialFilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.material_url
     *
     * @mbg.generated
     */
    private String materialUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.report_filename
     *
     * @mbg.generated
     */
    private String reportFilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.report_url
     *
     * @mbg.generated
     */
    private String reportUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table presentation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.id
     *
     * @return the value of presentation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.id
     *
     * @param id the value for presentation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.team_id
     *
     * @return the value of presentation.team_id
     *
     * @mbg.generated
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.team_id
     *
     * @param teamId the value for presentation.team_id
     *
     * @mbg.generated
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.score
     *
     * @return the value of presentation.score
     *
     * @mbg.generated
     */
    public Long getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.score
     *
     * @param score the value for presentation.score
     *
     * @mbg.generated
     */
    public void setScore(Long score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.report_score
     *
     * @return the value of presentation.report_score
     *
     * @mbg.generated
     */
    public Long getReportScore() {
        return reportScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.report_score
     *
     * @param reportScore the value for presentation.report_score
     *
     * @mbg.generated
     */
    public void setReportScore(Long reportScore) {
        this.reportScore = reportScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.seating_order
     *
     * @return the value of presentation.seating_order
     *
     * @mbg.generated
     */
    public Byte getSeatingOrder() {
        return seatingOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.seating_order
     *
     * @param seatingOrder the value for presentation.seating_order
     *
     * @mbg.generated
     */
    public void setSeatingOrder(Byte seatingOrder) {
        this.seatingOrder = seatingOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.seminard
     *
     * @return the value of presentation.seminard
     *
     * @mbg.generated
     */
    public Byte getSeminard() {
        return seminard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.seminard
     *
     * @param seminard the value for presentation.seminard
     *
     * @mbg.generated
     */
    public void setSeminard(Byte seminard) {
        this.seminard = seminard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.time
     *
     * @return the value of presentation.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.time
     *
     * @param time the value for presentation.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.material_filename
     *
     * @return the value of presentation.material_filename
     *
     * @mbg.generated
     */
    public String getMaterialFilename() {
        return materialFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.material_filename
     *
     * @param materialFilename the value for presentation.material_filename
     *
     * @mbg.generated
     */
    public void setMaterialFilename(String materialFilename) {
        this.materialFilename = materialFilename == null ? null : materialFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.material_url
     *
     * @return the value of presentation.material_url
     *
     * @mbg.generated
     */
    public String getMaterialUrl() {
        return materialUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.material_url
     *
     * @param materialUrl the value for presentation.material_url
     *
     * @mbg.generated
     */
    public void setMaterialUrl(String materialUrl) {
        this.materialUrl = materialUrl == null ? null : materialUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.report_filename
     *
     * @return the value of presentation.report_filename
     *
     * @mbg.generated
     */
    public String getReportFilename() {
        return reportFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.report_filename
     *
     * @param reportFilename the value for presentation.report_filename
     *
     * @mbg.generated
     */
    public void setReportFilename(String reportFilename) {
        this.reportFilename = reportFilename == null ? null : reportFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.report_url
     *
     * @return the value of presentation.report_url
     *
     * @mbg.generated
     */
    public String getReportUrl() {
        return reportUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.report_url
     *
     * @param reportUrl the value for presentation.report_url
     *
     * @mbg.generated
     */
    public void setReportUrl(String reportUrl) {
        this.reportUrl = reportUrl == null ? null : reportUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presentation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", teamId=").append(teamId);
        sb.append(", score=").append(score);
        sb.append(", reportScore=").append(reportScore);
        sb.append(", seatingOrder=").append(seatingOrder);
        sb.append(", seminard=").append(seminard);
        sb.append(", time=").append(time);
        sb.append(", materialFilename=").append(materialFilename);
        sb.append(", materialUrl=").append(materialUrl);
        sb.append(", reportFilename=").append(reportFilename);
        sb.append(", reportUrl=").append(reportUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}