package online.templab.flippedclass.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class Presentation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.course_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.seminar_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private Integer seminarId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.team_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private Integer teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.order
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private Integer order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presentation.score
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private BigDecimal score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table presentation
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.id
     *
     * @return the value of presentation.id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.id
     *
     * @param id the value for presentation.id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.course_id
     *
     * @return the value of presentation.course_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.course_id
     *
     * @param courseId the value for presentation.course_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.seminar_id
     *
     * @return the value of presentation.seminar_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public Integer getSeminarId() {
        return seminarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.seminar_id
     *
     * @param seminarId the value for presentation.seminar_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setSeminarId(Integer seminarId) {
        this.seminarId = seminarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.team_id
     *
     * @return the value of presentation.team_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.team_id
     *
     * @param teamId the value for presentation.team_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.order
     *
     * @return the value of presentation.order
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.order
     *
     * @param order the value for presentation.order
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presentation.score
     *
     * @return the value of presentation.score
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presentation.score
     *
     * @param score the value for presentation.score
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presentation
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", courseId=").append(courseId);
        sb.append(", seminarId=").append(seminarId);
        sb.append(", teamId=").append(teamId);
        sb.append(", order=").append(order);
        sb.append(", score=").append(score);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}