package online.templab.flippedclass.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class Question implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.presentation_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private Integer presentationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.team_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private Integer teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.student_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.score
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private BigDecimal score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.presentation_id
     *
     * @return the value of question.presentation_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public Integer getPresentationId() {
        return presentationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.presentation_id
     *
     * @param presentationId the value for question.presentation_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setPresentationId(Integer presentationId) {
        this.presentationId = presentationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.team_id
     *
     * @return the value of question.team_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.team_id
     *
     * @param teamId the value for question.team_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.student_id
     *
     * @return the value of question.student_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.student_id
     *
     * @param studentId the value for question.student_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.score
     *
     * @return the value of question.score
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.score
     *
     * @param score the value for question.score
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", presentationId=").append(presentationId);
        sb.append(", teamId=").append(teamId);
        sb.append(", studentId=").append(studentId);
        sb.append(", score=").append(score);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}