package online.templab.flippedclass.domain;

import java.io.Serializable;

public class Report implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.presentation_id
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private Integer presentationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.filename
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.url
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.score
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private Long score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.presentation_id
     *
     * @return the value of report.presentation_id
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public Integer getPresentationId() {
        return presentationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.presentation_id
     *
     * @param presentationId the value for report.presentation_id
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public void setPresentationId(Integer presentationId) {
        this.presentationId = presentationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.filename
     *
     * @return the value of report.filename
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.filename
     *
     * @param filename the value for report.filename
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.url
     *
     * @return the value of report.url
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.url
     *
     * @param url the value for report.url
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.score
     *
     * @return the value of report.score
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public Long getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.score
     *
     * @param score the value for report.score
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public void setScore(Long score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", presentationId=").append(presentationId);
        sb.append(", filename=").append(filename);
        sb.append(", url=").append(url);
        sb.append(", score=").append(score);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}