package online.templab.flippedclass.domain;

import java.io.Serializable;

public class Round implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round.max_sigh_up_num
     *
     * @mbg.generated
     */
    private Integer maxSighUpNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table round
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round.id
     *
     * @return the value of round.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round.id
     *
     * @param id the value for round.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round.course_id
     *
     * @return the value of round.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round.course_id
     *
     * @param courseId the value for round.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round.max_sigh_up_num
     *
     * @return the value of round.max_sigh_up_num
     *
     * @mbg.generated
     */
    public Integer getMaxSighUpNum() {
        return maxSighUpNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round.max_sigh_up_num
     *
     * @param maxSighUpNum the value for round.max_sigh_up_num
     *
     * @mbg.generated
     */
    public void setMaxSighUpNum(Integer maxSighUpNum) {
        this.maxSighUpNum = maxSighUpNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", courseId=").append(courseId);
        sb.append(", maxSighUpNum=").append(maxSighUpNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}