package online.templab.flippedclass.domain;

import java.io.Serializable;
import java.util.Date;

public class Seminar implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seminar.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seminar.topic
     *
     * @mbg.generated
     */
    private String topic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seminar.intro
     *
     * @mbg.generated
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seminar.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seminar.sign_up_start_time
     *
     * @mbg.generated
     */
    private Date signUpStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seminar.sign_up_end_time
     *
     * @mbg.generated
     */
    private Date signUpEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seminar.presentation_order_mode
     *
     * @mbg.generated
     */
    private Byte presentationOrderMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seminar.team_num_limit
     *
     * @mbg.generated
     */
    private Integer teamNumLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seminar.report_end_time
     *
     * @mbg.generated
     */
    private Date reportEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seminar
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seminar.id
     *
     * @return the value of seminar.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seminar.id
     *
     * @param id the value for seminar.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seminar.topic
     *
     * @return the value of seminar.topic
     *
     * @mbg.generated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seminar.topic
     *
     * @param topic the value for seminar.topic
     *
     * @mbg.generated
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seminar.intro
     *
     * @return the value of seminar.intro
     *
     * @mbg.generated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seminar.intro
     *
     * @param intro the value for seminar.intro
     *
     * @mbg.generated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seminar.state
     *
     * @return the value of seminar.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seminar.state
     *
     * @param state the value for seminar.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seminar.sign_up_start_time
     *
     * @return the value of seminar.sign_up_start_time
     *
     * @mbg.generated
     */
    public Date getSignUpStartTime() {
        return signUpStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seminar.sign_up_start_time
     *
     * @param signUpStartTime the value for seminar.sign_up_start_time
     *
     * @mbg.generated
     */
    public void setSignUpStartTime(Date signUpStartTime) {
        this.signUpStartTime = signUpStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seminar.sign_up_end_time
     *
     * @return the value of seminar.sign_up_end_time
     *
     * @mbg.generated
     */
    public Date getSignUpEndTime() {
        return signUpEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seminar.sign_up_end_time
     *
     * @param signUpEndTime the value for seminar.sign_up_end_time
     *
     * @mbg.generated
     */
    public void setSignUpEndTime(Date signUpEndTime) {
        this.signUpEndTime = signUpEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seminar.presentation_order_mode
     *
     * @return the value of seminar.presentation_order_mode
     *
     * @mbg.generated
     */
    public Byte getPresentationOrderMode() {
        return presentationOrderMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seminar.presentation_order_mode
     *
     * @param presentationOrderMode the value for seminar.presentation_order_mode
     *
     * @mbg.generated
     */
    public void setPresentationOrderMode(Byte presentationOrderMode) {
        this.presentationOrderMode = presentationOrderMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seminar.team_num_limit
     *
     * @return the value of seminar.team_num_limit
     *
     * @mbg.generated
     */
    public Integer getTeamNumLimit() {
        return teamNumLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seminar.team_num_limit
     *
     * @param teamNumLimit the value for seminar.team_num_limit
     *
     * @mbg.generated
     */
    public void setTeamNumLimit(Integer teamNumLimit) {
        this.teamNumLimit = teamNumLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seminar.report_end_time
     *
     * @return the value of seminar.report_end_time
     *
     * @mbg.generated
     */
    public Date getReportEndTime() {
        return reportEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seminar.report_end_time
     *
     * @param reportEndTime the value for seminar.report_end_time
     *
     * @mbg.generated
     */
    public void setReportEndTime(Date reportEndTime) {
        this.reportEndTime = reportEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seminar
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", topic=").append(topic);
        sb.append(", intro=").append(intro);
        sb.append(", state=").append(state);
        sb.append(", signUpStartTime=").append(signUpStartTime);
        sb.append(", signUpEndTime=").append(signUpEndTime);
        sb.append(", presentationOrderMode=").append(presentationOrderMode);
        sb.append(", teamNumLimit=").append(teamNumLimit);
        sb.append(", reportEndTime=").append(reportEndTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}