package online.templab.flippedclass.domain;

import java.io.Serializable;
import java.util.Date;

public class ShareApplication implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_application.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_application.master_course_id
     *
     * @mbg.generated
     */
    private Integer masterCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_application.slave_course_id
     *
     * @mbg.generated
     */
    private Integer slaveCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_application.function
     *
     * @mbg.generated
     */
    private Byte function;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_application.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_application.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table share_application
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_application.id
     *
     * @return the value of share_application.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_application.id
     *
     * @param id the value for share_application.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_application.master_course_id
     *
     * @return the value of share_application.master_course_id
     *
     * @mbg.generated
     */
    public Integer getMasterCourseId() {
        return masterCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_application.master_course_id
     *
     * @param masterCourseId the value for share_application.master_course_id
     *
     * @mbg.generated
     */
    public void setMasterCourseId(Integer masterCourseId) {
        this.masterCourseId = masterCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_application.slave_course_id
     *
     * @return the value of share_application.slave_course_id
     *
     * @mbg.generated
     */
    public Integer getSlaveCourseId() {
        return slaveCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_application.slave_course_id
     *
     * @param slaveCourseId the value for share_application.slave_course_id
     *
     * @mbg.generated
     */
    public void setSlaveCourseId(Integer slaveCourseId) {
        this.slaveCourseId = slaveCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_application.function
     *
     * @return the value of share_application.function
     *
     * @mbg.generated
     */
    public Byte getFunction() {
        return function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_application.function
     *
     * @param function the value for share_application.function
     *
     * @mbg.generated
     */
    public void setFunction(Byte function) {
        this.function = function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_application.state
     *
     * @return the value of share_application.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_application.state
     *
     * @param state the value for share_application.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_application.create_time
     *
     * @return the value of share_application.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_application.create_time
     *
     * @param createTime the value for share_application.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_application
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", masterCourseId=").append(masterCourseId);
        sb.append(", slaveCourseId=").append(slaveCourseId);
        sb.append(", function=").append(function);
        sb.append(", state=").append(state);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}