package online.templab.flippedclass.domain;

import java.io.Serializable;

public class ShareApplication implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_application.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_application.master_course_id
     *
     * @mbg.generated
     */
    private Integer masterCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_application.slave_course_id
     *
     * @mbg.generated
     */
    private Integer slaveCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_application.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table share_application
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_application.id
     *
     * @return the value of share_application.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_application.id
     *
     * @param id the value for share_application.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_application.master_course_id
     *
     * @return the value of share_application.master_course_id
     *
     * @mbg.generated
     */
    public Integer getMasterCourseId() {
        return masterCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_application.master_course_id
     *
     * @param masterCourseId the value for share_application.master_course_id
     *
     * @mbg.generated
     */
    public void setMasterCourseId(Integer masterCourseId) {
        this.masterCourseId = masterCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_application.slave_course_id
     *
     * @return the value of share_application.slave_course_id
     *
     * @mbg.generated
     */
    public Integer getSlaveCourseId() {
        return slaveCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_application.slave_course_id
     *
     * @param slaveCourseId the value for share_application.slave_course_id
     *
     * @mbg.generated
     */
    public void setSlaveCourseId(Integer slaveCourseId) {
        this.slaveCourseId = slaveCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_application.type
     *
     * @return the value of share_application.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_application.type
     *
     * @param type the value for share_application.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_application
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", masterCourseId=").append(masterCourseId);
        sb.append(", slaveCourseId=").append(slaveCourseId);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}