package online.templab.flippedclass.domain;

import java.io.Serializable;

public class StudentKlass implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_klass.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_klass.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_klass.klass_id
     *
     * @mbg.generated
     */
    private Integer klassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_klass
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_klass.id
     *
     * @return the value of student_klass.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_klass.id
     *
     * @param id the value for student_klass.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_klass.user_id
     *
     * @return the value of student_klass.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_klass.user_id
     *
     * @param userId the value for student_klass.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_klass.klass_id
     *
     * @return the value of student_klass.klass_id
     *
     * @mbg.generated
     */
    public Integer getKlassId() {
        return klassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_klass.klass_id
     *
     * @param klassId the value for student_klass.klass_id
     *
     * @mbg.generated
     */
    public void setKlassId(Integer klassId) {
        this.klassId = klassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_klass
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", klassId=").append(klassId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}