package online.templab.flippedclass.domain;

import java.io.Serializable;

public class Team implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.leader_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private Integer leaderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.name
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.valid
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private Boolean valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table team
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.id
     *
     * @return the value of team.id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.id
     *
     * @param id the value for team.id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.leader_id
     *
     * @return the value of team.leader_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public Integer getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.leader_id
     *
     * @param leaderId the value for team.leader_id
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setLeaderId(Integer leaderId) {
        this.leaderId = leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.name
     *
     * @return the value of team.name
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.name
     *
     * @param name the value for team.name
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.valid
     *
     * @return the value of team.valid
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.valid
     *
     * @param valid the value for team.valid
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbg.generated Sun Dec 02 14:03:43 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", leaderId=").append(leaderId);
        sb.append(", name=").append(name);
        sb.append(", valid=").append(valid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}