package online.templab.flippedclass.domain;

import java.io.Serializable;
import java.util.Date;

public class TeamRule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_rule.id
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_rule.course_id
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_rule.strategy
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private Integer strategy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_rule.max_member_num
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private Integer maxMemberNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_rule.min_member_num
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private Integer minMemberNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_rule.end_time
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table team_rule
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_rule.id
     *
     * @return the value of team_rule.id
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_rule.id
     *
     * @param id the value for team_rule.id
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_rule.course_id
     *
     * @return the value of team_rule.course_id
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_rule.course_id
     *
     * @param courseId the value for team_rule.course_id
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_rule.strategy
     *
     * @return the value of team_rule.strategy
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public Integer getStrategy() {
        return strategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_rule.strategy
     *
     * @param strategy the value for team_rule.strategy
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public void setStrategy(Integer strategy) {
        this.strategy = strategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_rule.max_member_num
     *
     * @return the value of team_rule.max_member_num
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public Integer getMaxMemberNum() {
        return maxMemberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_rule.max_member_num
     *
     * @param maxMemberNum the value for team_rule.max_member_num
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public void setMaxMemberNum(Integer maxMemberNum) {
        this.maxMemberNum = maxMemberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_rule.min_member_num
     *
     * @return the value of team_rule.min_member_num
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public Integer getMinMemberNum() {
        return minMemberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_rule.min_member_num
     *
     * @param minMemberNum the value for team_rule.min_member_num
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public void setMinMemberNum(Integer minMemberNum) {
        this.minMemberNum = minMemberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_rule.end_time
     *
     * @return the value of team_rule.end_time
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_rule.end_time
     *
     * @param endTime the value for team_rule.end_time
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_rule
     *
     * @mbg.generated Sun Dec 02 14:03:44 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", courseId=").append(courseId);
        sb.append(", strategy=").append(strategy);
        sb.append(", maxMemberNum=").append(maxMemberNum);
        sb.append(", minMemberNum=").append(minMemberNum);
        sb.append(", endTime=").append(endTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}