package online.templab.flippedclass.domain;

import java.io.Serializable;
import java.util.Date;

public class TeamRule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_rule.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_rule.max_member_num
     *
     * @mbg.generated
     */
    private Integer maxMemberNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_rule.min_member_num
     *
     * @mbg.generated
     */
    private Integer minMemberNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_rule.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table team_rule
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_rule.id
     *
     * @return the value of team_rule.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_rule.id
     *
     * @param id the value for team_rule.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_rule.max_member_num
     *
     * @return the value of team_rule.max_member_num
     *
     * @mbg.generated
     */
    public Integer getMaxMemberNum() {
        return maxMemberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_rule.max_member_num
     *
     * @param maxMemberNum the value for team_rule.max_member_num
     *
     * @mbg.generated
     */
    public void setMaxMemberNum(Integer maxMemberNum) {
        this.maxMemberNum = maxMemberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_rule.min_member_num
     *
     * @return the value of team_rule.min_member_num
     *
     * @mbg.generated
     */
    public Integer getMinMemberNum() {
        return minMemberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_rule.min_member_num
     *
     * @param minMemberNum the value for team_rule.min_member_num
     *
     * @mbg.generated
     */
    public void setMinMemberNum(Integer minMemberNum) {
        this.minMemberNum = minMemberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_rule.end_time
     *
     * @return the value of team_rule.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_rule.end_time
     *
     * @param endTime the value for team_rule.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_rule
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", maxMemberNum=").append(maxMemberNum);
        sb.append(", minMemberNum=").append(minMemberNum);
        sb.append(", endTime=").append(endTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}